services:
  boilerplate-api-db:
    image: postgres:latest
    container_name: boilerplate-api-db
    restart: always
    environment:
      - POSTGRES_USER=app_user               # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=myHardCoreDevDb123 # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=HeroDb                   # The PostgreSQL default database (automatically created at first launch)
    networks:
      - moordevnet
    ports:
      - "5432:5432"
  
  boilerplate-api:
    image: boilerplate-api:local
    container_name: boilerplate-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile
    depends_on:
      - boilerplate-api-db
    networks:
      - moordevnet

networks:
  moordevnet:
    name: moordevnet