services:
  boilerplate-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=boilerplate-api-db;Port=5432;Database=HeroDb;Username=app_user;Password=myHardCoreDevDb123
    networks:
      - moordevnet
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./https:/https/:ro